# Generated by Django 2.2.4 on 2019-08-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_kievjavascript'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KievJavascript',
            new_name='KievPars',
        ),
    ]
